### ISSUE TITLE
add smileys

### ISSUE THREAD

**Issue by flying-sheep** [kragen/xcompose#19]
hi, there’s a number of smileys we could add, and i filed this bug for input. so we have:
- :) → ☺
- (: → ☻

but there’s [much more](http://stackoverflow.com/questions/29488143/is-there-an-equivalence-table-to-convert-ascii-smileys-to-unicode-emojis)

at least for some, e.g. ;) i really expect them to exist 😉

**Comment by clsn** [comment]
See the emoji.compose supplement.
