### ISSUE TITLE
Bitcoin now has a specific unicode char

### ISSUE THREAD

**Issue by the9ull** [kragen/xcompose#22]
It was approved recently, so the fonts doesn't support it yet. When we should update the compose binding?
The new code is U+20BF ₿
The old was U+0E3F ฿

Should we remove the other signs?
Ƀ and ƀ

**Comment by clsn** [comment]
Unicode 10 isn't *officially* adopted yet, at the time of this writing (more than a year after the comment!)  When it is, it should be added.

**Comment by clsn** [comment]
It's been added, but the character in the file is still wrong (though the codepoint listed is correct).  This will be fixed Real Soon Now, when I push.
