### ISSUE TITLE
how does one key <Multi_key> <Multi_key> modifiers?

### ISSUE THREAD

**Issue by scruss** [kragen/xcompose#26]
My standard single <Multi_key> definitions are working, but none with the double `<Multi_key> <Multi_key>` def. How would these be keyed; Compose+Shift?

**Comment by MD-ThorErik** [comment]
Pressing the compose key twice... I have sticky keys set, and some of them work, but mos of them don't... i.e Compose-Compose y y for "☯", but not Compose-Compose p l a n e, which writes "ane"

**Comment by clsn** [comment]
Multi_key isn't supposed to be a modifier, so I would expect sticky keys to leave it alone.  Hitting the Multi_key twice should work.  You might want to try running xev and seeing what the keystrokes you're generating are.
