### ISSUE TITLE
Instructions about restarting

### ISSUE THREAD

**Issue by spookylukey** [kragen/xcompose#27]
I'm guessing I need to restart X for this to take effect?

Is there an easier way, especially for trying out my own additions?

Thanks!

**Comment by MD-ThorErik** [comment]
I kill telescope and launch the recompiled executable, maybe doing a sudo make install...
`killall telescope && telescope &`

**Comment by MD-ThorErik** [comment]
It's works per app. Some apps work better than others with the XCompose... So, you need to relaunch the app in which you enter the text...

**Comment by spookylukey** [comment]
Thanks, I added a PR to make a note of this. The first app I tried to use apparently doesn't support XCompose (though it does support the other combinations in /usr/share/... )

**Comment by clsn** [comment]
I've found that when you change .XCompose, it only affects apps that are *started* after the change.  But you don't need to restart all of X.

**Comment by clsn** [comment]
Merged.
